*** empty log message ***
git-svn-id: https://svn.kannel.org/gateway/trunk@2221 a7d65f57-29cd-40c9-b71e-ebca51ad1b1d

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -65,6 +65,33 @@ fi
 AC_CHECK_LIB(resolv, inet_ntop)
 
 
+dnl Check to see if we should do the WTLS thing, and which version to use
+
+AC_ARG_WITH(wtls,
+[  --with-wtls             select wtls version to use: openssl/baltimore], [
+  case "$withval" in
+  openssl) echo "OpenSSL WTLS selected, attempting to find libraries..."
+	OLDLIBS="$LIBS"
+	LIBS="$LIBS -L/usr/local/ssl/lib -lcrypto"
+	AC_CHECK_LIB(crypto, RSA_new,
+	[
+		echo "OpenSSL found; WTLS enabled"
+		CFLAGS="$CFLAGS -I/usr/local/ssl/include"
+		AC_DEFINE(HAVE_WTLS_OPENSSL)
+	],
+	[
+		LIBS=$OLDLIBS
+		echo "OpenSSL not found; WTLS disabled"
+	]
+	)
+	;;
+  baltimore) echo "Baltimore WTLS not available" ;;
+  *) echo "Unknown wtls version $withval. Oops."; exit 1 ;;
+  esac
+]
+)
+
+
 dnl Checks for header files.
 
 AC_HEADER_STDC
