2003-07-02  Alexander Malysh  <a.malysh@centrium.de>     * configure.in,configure: added ability to biuld in more as one DLR storage type.       Just call: ./configure --enable-mysql --enable-sdb --with-dlr="mysql sdb"       in this case we have mysql and sdb support build in.
git-svn-id: https://svn.kannel.org/gateway/trunk@3658 a7d65f57-29cd-40c9-b71e-ebca51ad1b1d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -66,7 +66,7 @@ ac_help="$ac_help
 ac_help="$ac_help
   --enable-sdb            enable LibSDB storage (default: disabled)"
 ac_help="$ac_help
-  --with-dlr[=TYPE]       select DLR storage to use: internal/mysql/sdb (default: internal)"
+  --with-dlr[=TYPE TYPE]  select DLR storage to use: internal/mysql/sdb (default: internal)"
 ac_help="$ac_help
   --with-wtls[=TYPE]      select WTLS version to use: openssl/baltimore"
 
@@ -3920,37 +3920,41 @@ if test "${with_dlr+set}" = set; then
 '
   echo "${nl}${T_MD}Configuring DLR support ...${T_ME}"
  
-  echo $ac_n "checking for DLR storage type""... $ac_c" 1>&6
-echo "configure:3925: checking for DLR storage type" >&5
-  echo "$ac_t""$withval" 1>&6
-  case "$withval" in
-  internal)
-    ;;
-  mysql)
-    if test "$MYSQL" != "yes"; then
-      { echo "configure: error: Option --with-dlr=mysql requires MySQL client support" 1>&2; exit 1; }
-    else
-      cat >> confdefs.h <<\EOF
+  for myval in $withval
+  do
+      echo $ac_n "checking for DLR storage type $myval""... $ac_c" 1>&6
+echo "configure:3927: checking for DLR storage type $myval" >&5
+      case "$myval" in
+      internal)
+          ;;
+      mysql)
+        if test "$MYSQL" != "yes"; then
+          { echo "configure: error: Option --with-dlr=mysql requires MySQL client support" 1>&2; exit 1; }
+        else
+          echo "$ac_t""enabled" 1>&6
+          cat >> confdefs.h <<\EOF
 #define DLR_MYSQL 1
 EOF
 
-    fi
-    ;;
-  sdb)
-    if test "$SDB" != "yes"; then
-      { echo "configure: error: Option --with-dlr=sdb requires SDB support" 1>&2; exit 1; }
-    else
-      cat >> confdefs.h <<\EOF
+        fi
+        ;;
+      sdb)
+        if test "$SDB" != "yes"; then
+          { echo "configure: error: Option --with-dlr=sdb requires SDB support" 1>&2; exit 1; }
+        else
+          cat >> confdefs.h <<\EOF
 #define DLR_SDB 1
 EOF
 
-    fi
-    ;;
-  *) 
-    { echo "configure: error: Unknown DLR storage support!" 1>&2; exit 1; }
-    exit 1 
-    ;;
-  esac
+          echo "$ac_t""enabled" 1>&6
+        fi
+        ;;
+      *) 
+        { echo "configure: error: Unknown DLR storage support!" 1>&2; exit 1; }
+        exit 1 
+        ;;
+      esac
+  done
 
 fi
 
@@ -3966,14 +3970,14 @@ if test "${with_wtls+set}" = set; then
   echo "${nl}${T_MD}Configuring WTLS support ...${T_ME}"
  
   echo $ac_n "checking for WTLS library""... $ac_c" 1>&6
-echo "configure:3970: checking for WTLS library" >&5
+echo "configure:3974: checking for WTLS library" >&5
   echo "$ac_t""$withval" 1>&6
   case "$withval" in
   openssl) 
  	OLDLIBS="$LIBS"
 	LIBS="$LIBS -L/usr/local/ssl/lib -lcrypto"
     echo $ac_n "checking for RSA_new in -lcrypto""... $ac_c" 1>&6
-echo "configure:3977: checking for RSA_new in -lcrypto" >&5
+echo "configure:3981: checking for RSA_new in -lcrypto" >&5
 ac_lib_var=`echo crypto'_'RSA_new | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3981,7 +3985,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcrypto  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3985 "configure"
+#line 3989 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3992,7 +3996,7 @@ int main() {
 RSA_new()
 ; return 0; }
 EOF
-if { (eval echo configure:3996: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4000: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -4011,17 +4015,17 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:4015: checking for $ac_hdr" >&5
+echo "configure:4019: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 4020 "configure"
+#line 4024 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:4025: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:4029: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
